// <auto-generated>
// This is a generated file. Manual changes may be overwritten.
// </auto-generated>

#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SpayWise.Data.Conventions;

namespace SpayWise.Data;

public enum BuiltInAppointmentType
{
	SpayNeuter = 1,
	Wellness = 2,
	Recheck = 3
}

public class AppointmentType : BaseTable
{
	public int ClinicId { get; set; }
	public string Name { get; set; } = default!;
	public BuiltInAppointmentType BuiltInType { get; set; }
	public string? BackColor { get; set; }
	public string? TextColor { get; set; }
	public bool IsActive { get; set; } = true;

	public Clinic? Clinic { get; set; }
}

public class AppointmentTypeConfiguration : IEntityTypeConfiguration<AppointmentType>
{
	public void Configure(EntityTypeBuilder<AppointmentType> builder)
	{
		builder.Property(a => a.Name).IsRequired().HasMaxLength(50);
		builder.Property(a => a.BackColor).HasMaxLength(20);
		builder.Property(a => a.TextColor).HasMaxLength(20);

		builder.HasOne(a => a.Clinic)
			.WithMany(e => e.AppointmentTypes)
			.HasForeignKey(a => a.ClinicId)
			.OnDelete(DeleteBehavior.Restrict);

		builder.HasIndex(a => new { a.ClinicId, a.Name }).IsUnique();
	}
}
