// <auto-generated>
// This is a generated file. Manual changes may be overwritten.
// </auto-generated>

#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SpayWise.Data.Conventions;

namespace SpayWise.Data;

public class CountLimitOverride : BaseTable
{
	public int LocationId { get; set; }
	public DateOnly Date { get; set; }
	public int Maximum { get; set; }
	public string? Comments { get; set; }

	public Location? Location { get; set; }
}

public class SexSpeciesCountOverrideConfiguration : IEntityTypeConfiguration<CountLimitOverride>
{
	public void Configure(EntityTypeBuilder<CountLimitOverride> builder)
	{
		builder.Property(s => s.Comments).HasMaxLength(255);

		builder.HasOne(s => s.Location)
			.WithMany(e => e.OverrideCounts)
			.HasForeignKey(s => s.LocationId)
			.OnDelete(DeleteBehavior.Restrict);

		builder.HasIndex(s => new { s.LocationId, s.Date }).IsUnique();
	}
}
