// <auto-generated>
// This is a generated file. Manual changes may be overwritten.
// </auto-generated>

#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SpayWise.Data.Conventions;

namespace SpayWise.Data;

public class DailyPointsLimit : BaseTable
{
	public int LocationId { get; set; }
	public int DayOfWeek { get; set; }
	public int Maximum { get; set; }

	public Location? Location { get; set; }
}

public class SexSpeciesPointsDailyConfiguration : IEntityTypeConfiguration<DailyPointsLimit>
{
	public void Configure(EntityTypeBuilder<DailyPointsLimit> builder)
	{
		builder.HasOne(s => s.Location)
			.WithMany(e => e.DailyPoints)
			.HasForeignKey(s => s.LocationId)
			.OnDelete(DeleteBehavior.Restrict);

		builder.HasIndex(s => new { s.LocationId, s.DayOfWeek }).IsUnique();
	}
}
