// <auto-generated>
// This is a generated file. Manual changes may be overwritten.
// </auto-generated>

#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SpayWise.Data.Conventions;

namespace SpayWise.Data;

public class DailyCountLimit : BaseTable
{
	public int LocationId { get; set; }
	public int DayOfWeek { get; set; }
	public int SexId { get; set; }
	public int SpeciesId { get; set; }
	public int Maximum { get; set; }

	public Location? Location { get; set; }
	public Sex? Sex { get; set; }
	public Species? Species { get; set; }
}

public class SexSpeciesCountDailyConfiguration : IEntityTypeConfiguration<DailyCountLimit>
{
	public void Configure(EntityTypeBuilder<DailyCountLimit> builder)
	{
		builder.HasOne(s => s.Location)
			.WithMany(e => e.DailyCounts)
			.HasForeignKey(s => s.LocationId)
			.OnDelete(DeleteBehavior.Restrict);

		builder.HasOne(s => s.Sex)
			.WithMany(e => e.DailyCountLimits)
			.HasForeignKey(s => s.SexId)
			.OnDelete(DeleteBehavior.Restrict);

		builder.HasOne(s => s.Species)
			.WithMany(e => e.DailyCountLimits)
			.HasForeignKey(s => s.SpeciesId)
			.OnDelete(DeleteBehavior.Restrict);

		builder.HasIndex(s => new { s.LocationId, s.DayOfWeek, s.SexId, s.SpeciesId }).IsUnique();
	}
}
