// <auto-generated>
// This is a generated file. Manual changes may be overwritten.
// </auto-generated>

#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SpayWise.Data.Conventions;

namespace SpayWise.Data;

public class Location : BaseTable
{
	public int ClinicId { get; set; }
	public string Name { get; set; } = default!;
	public string? Address1 { get; set; }
	public string? Address2 { get; set; }
	public string? City { get; set; } 
	public string? State { get; set; }
	public string? ZipCode { get; set; }
	public string? Phone { get; set; }

	public Clinic? Clinic { get; set; }
}

public class LocationConfiguration : IEntityTypeConfiguration<Location>
{
	public void Configure(EntityTypeBuilder<Location> builder)
	{
		builder.Property(l => l.Name).IsRequired().HasMaxLength(50);

		builder.HasOne(l => l.Clinic)
			.WithMany(e => e.Locations)
			.HasForeignKey(l => l.ClinicId)
			.OnDelete(DeleteBehavior.Restrict);

		builder.HasIndex(e => new { e.ClinicId, e.Name }).IsUnique();
	}
}
