// <auto-generated>
// This is a generated file. Manual changes may be overwritten.
// </auto-generated>

#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SpayWise.Data.Conventions;

namespace SpayWise.Data;

public class PaymentMethod : BaseTable
{
	public int ClinicId { get; set; }
	public string Name { get; set; } = default!;
	public string Data { get; set; } = default!;
	public bool IsActive { get; set; } = true;

	public Clinic? Clinic { get; set; }
}

public class PaymentMethodConfiguration : IEntityTypeConfiguration<PaymentMethod>
{
	public void Configure(EntityTypeBuilder<PaymentMethod> builder)
	{
		builder.Property(p => p.Name).IsRequired().HasMaxLength(50);
		builder.Property(p => p.Data).IsRequired().HasMaxLength(500);

		builder.HasOne(p => p.Clinic)
			.WithMany(e => e.PaymentMethods)
			.HasForeignKey(p => p.ClinicId)
			.OnDelete(DeleteBehavior.Restrict);

		builder.HasIndex(p => new { p.ClinicId, p.Name }).IsUnique();
	}
}
