// <auto-generated>
// This is a generated file. Manual changes may be overwritten.
// </auto-generated>

#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SpayWise.Data.Conventions;

namespace SpayWise.Data;

public class Species : BaseTable
{
	public int ClinicId { get; set; }
	public string Name { get; set; } = default!;
	public string BaseName { get; set; } = default!;
	public string Abbreviation { get; set; } = default!;
	public int AppSpeciesId { get; set; }
	public int? MinWeight { get; set; }
	public bool IsActive { get; set; } = true;

	public Clinic? Clinic { get; set; }
	public AppSpecies? AppSpecies { get; set; }
}

public class SpeciesConfiguration : IEntityTypeConfiguration<Species>
{
	public void Configure(EntityTypeBuilder<Species> builder)
	{
		builder.Property(s => s.Name).IsRequired().HasMaxLength(50);
		builder.Property(s => s.BaseName).IsRequired().HasMaxLength(50);
		builder.Property(s => s.Abbreviation).IsRequired().HasMaxLength(10);

		builder.HasOne(s => s.Clinic)
			.WithMany(e => e.Species)
			.HasForeignKey(s => s.ClinicId)
			.OnDelete(DeleteBehavior.Restrict);

		builder.HasIndex(s => new { s.ClinicId, s.Name }).IsUnique();
	}
}
