// <auto-generated>
// This is a generated file. Manual changes may be overwritten.
// </auto-generated>

#nullable enable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SpayWise.Data.Conventions;

namespace SpayWise.Data;

public class Veterinarian : BaseTable
{
	public int ClinicId { get; set; }
	public string LastName { get; set; } = default!;
	public string FirstName { get; set; } = default!;
	public string LicenseNumber { get; set; } = default!;
	public string? ImageHref { get; set; }
	public bool IsActive { get; set; } = true;
}

public class VeterinarianConfiguration : IEntityTypeConfiguration<Veterinarian>
{
	public void Configure(EntityTypeBuilder<Veterinarian> builder)
	{
		builder.Property(v => v.LastName).IsRequired().HasMaxLength(50);
		builder.Property(v => v.FirstName).IsRequired().HasMaxLength(50);
		builder.Property(v => v.LicenseNumber).IsRequired().HasMaxLength(50);
		builder.Property(v => v.ImageHref).HasMaxLength(50);
	}
}
